[2022-09-08T10:32:05.876+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2021-08-03T00:00:00+00:00 [queued]>
[2022-09-08T10:32:06.026+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2021-08-03T00:00:00+00:00 [queued]>
[2022-09-08T10:32:06.034+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-08T10:32:06.035+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2022-09-08T10:32:06.036+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-08T10:32:06.169+0000] {taskinstance.py:1389} INFO - Executing <Task(BashOperator): second_task> on 2021-08-03 00:00:00+00:00
[2022-09-08T10:32:06.208+0000] {standard_task_runner.py:52} INFO - Started process 3347 to run task
[2022-09-08T10:32:06.244+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v5', 'second_task', 'scheduled__2021-08-03T00:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/example_dags.py', '--cfg-path', '/tmp/tmphp72sp3f', '--error-file', '/tmp/tmp23twpion']
[2022-09-08T10:32:06.263+0000] {standard_task_runner.py:80} INFO - Job 33: Subtask second_task
[2022-09-08T10:32:06.977+0000] {task_command.py:371} INFO - Running <TaskInstance: our_first_dag_v5.second_task scheduled__2021-08-03T00:00:00+00:00 [running]> on host c56eb7ae2624
[2022-09-08T10:32:14.262+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag_v5
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2021-08-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-03T00:00:00+00:00
[2022-09-08T10:32:14.298+0000] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-09-08T10:32:14.318+0000] {subprocess.py:74} INFO - Running command: ['/bin/bash', '-c', 'echo hey, I am task2 and will be running after task1!']
[2022-09-08T10:32:14.539+0000] {subprocess.py:85} INFO - Output:
[2022-09-08T10:32:14.547+0000] {subprocess.py:92} INFO - hey, I am task2 and will be running after task1!
[2022-09-08T10:32:14.562+0000] {subprocess.py:96} INFO - Command exited with return code 0
[2022-09-08T10:32:15.505+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=second_task, execution_date=20210803T000000, start_date=20220908T103205, end_date=20220908T103215
[2022-09-08T10:32:16.843+0000] {local_task_job.py:227} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-09-08T10:32:16.940+0000] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 3347. PIDs of all processes in the group: [3347]
[2022-09-08T10:32:16.947+0000] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 3347
[2022-09-08T10:32:17.008+0000] {process_utils.py:75} INFO - Process psutil.Process(pid=3347, status='terminated', exitcode=0, started='10:32:05') (3347) terminated with exit code 0
