[2022-09-08T10:32:38.013+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2021-08-20T00:00:00+00:00 [queued]>
[2022-09-08T10:32:38.124+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2021-08-20T00:00:00+00:00 [queued]>
[2022-09-08T10:32:38.126+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-08T10:32:38.129+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2022-09-08T10:32:38.131+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-08T10:32:38.313+0000] {taskinstance.py:1389} INFO - Executing <Task(BashOperator): second_task> on 2021-08-20 00:00:00+00:00
[2022-09-08T10:32:38.355+0000] {standard_task_runner.py:52} INFO - Started process 3519 to run task
[2022-09-08T10:32:38.386+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v5', 'second_task', 'scheduled__2021-08-20T00:00:00+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/example_dags.py', '--cfg-path', '/tmp/tmp3mlw4bs8', '--error-file', '/tmp/tmpqc8umtlw']
[2022-09-08T10:32:38.404+0000] {standard_task_runner.py:80} INFO - Job 84: Subtask second_task
[2022-09-08T10:32:38.855+0000] {task_command.py:371} INFO - Running <TaskInstance: our_first_dag_v5.second_task scheduled__2021-08-20T00:00:00+00:00 [running]> on host c56eb7ae2624
[2022-09-08T10:32:42.425+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag_v5
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2021-08-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-20T00:00:00+00:00
[2022-09-08T10:32:42.443+0000] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-09-08T10:32:42.454+0000] {subprocess.py:74} INFO - Running command: ['/bin/bash', '-c', 'echo hey, I am task2 and will be running after task1!']
[2022-09-08T10:32:42.573+0000] {subprocess.py:85} INFO - Output:
[2022-09-08T10:32:42.616+0000] {subprocess.py:92} INFO - hey, I am task2 and will be running after task1!
[2022-09-08T10:32:42.639+0000] {subprocess.py:96} INFO - Command exited with return code 0
[2022-09-08T10:32:43.581+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=second_task, execution_date=20210820T000000, start_date=20220908T103238, end_date=20220908T103243
[2022-09-08T10:32:44.068+0000] {local_task_job.py:227} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-09-08T10:32:44.157+0000] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 3519. PIDs of all processes in the group: [3519]
[2022-09-08T10:32:44.175+0000] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 3519
[2022-09-08T10:32:44.926+0000] {process_utils.py:75} INFO - Process psutil.Process(pid=3519, status='terminated', exitcode=0, started='10:32:38') (3519) terminated with exit code 0
